package com.homecam.activity;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.*;import com.google.android.material.button.MaterialButton;import com.google.android.material.card.MaterialCardView;import com.google.android.material.materialswitch.MaterialSwitch;import com.google.android.material.textfield.*;import com.homecam.R;import com.homecam.database.SettingsStore;import com.homecam.model.Command;import com.homecam.network.WorkerClient;import com.homecam.service.StreamingService;import com.homecam.utils.*;import org.webrtc.*;import java.util.*;import java.util.concurrent.*;

/** Main single-APK experience for selecting Camera or Viewer mode and controlling P2P sessions. */
public final class MainActivity extends AppCompatActivity { private SettingsStore store; private LinearLayout root; private SurfaceViewRenderer renderer; private final ExecutorService io=Executors.newSingleThreadExecutor(); private String sessionToken=Validators.newSessionToken();
 protected void onCreate(Bundle b){super.onCreate(b);store=new SettingsStore(this);showHome();requestBatteryExemption();}
 private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24);root.setGravity(Gravity.CENTER_HORIZONTAL);setContentView(root);} private TextView title(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(28);v.setPadding(0,0,0,24);root.addView(v);return v;} private MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setCornerRadius(16);root.addView(b,new LinearLayout.LayoutParams(-1,-2));return b;}
 private void showHome(){base();title("HomeCam");btn("Camera Device").setOnClickListener(v->showCamera());btn("Viewer Device").setOnClickListener(v->showViewer());btn("Settings").setOnClickListener(v->showSettings());}
 private void showCamera(){base();title("Camera Mode");TextView id=title("Device ID: "+store.getDeviceId());MaterialButton start=btn("Start foreground camera");MaterialButton stop=btn("Stop camera");btn("Back").setOnClickListener(v->showHome());start.setOnClickListener(v->{if(hasMediaPermissions()){ContextCompat.startForegroundService(this,new Intent(this,StreamingService.class));}else requestPermissions();});stop.setOnClickListener(v->startService(new Intent(this,StreamingService.class).setAction(StreamingService.ACTION_STOP)));}
 private void showViewer(){base();title("Viewer Mode");TextInputEditText device=new TextInputEditText(this);device.setHint(getString(R.string.device_id_hint));device.setText(store.getDeviceId());TextInputLayout box=new TextInputLayout(this);box.addView(device);root.addView(box,new LinearLayout.LayoutParams(-1,-2));renderer=new SurfaceViewRenderer(this);renderer.init(EglBase.create().getEglBaseContext(),null);root.addView(renderer,new LinearLayout.LayoutParams(-1,0,1));addCommandButton("START CAMERA",device,Command.START);addCommandButton("STOP CAMERA",device,Command.STOP);addCommandButton("FRONT CAMERA",device,Command.FRONT_CAMERA);addCommandButton("BACK CAMERA",device,Command.BACK_CAMERA);addCommandButton("FLASH",device,Command.FLASH_ON);addCommandButton("MUTE",device,Command.DISABLE_AUDIO);addCommandButton("HD",device,Command.HD_ON);addCommandButton("Reconnect",device,Command.PING);btn("Back").setOnClickListener(v->showHome());}
 private void addCommandButton(String label,TextInputEditText d,Command c){btn(label).setOnClickListener(v->{String id=String.valueOf(d.getText()); if(!Validators.isValidDeviceId(id)){toast("Invalid Device ID");return;} io.execute(()->{try{new WorkerClient(store.getWorkerUrl()).postCommand(id,sessionToken,c);runOnUiThread(()->toast(c.name()+" sent"));}catch(Exception e){Logger.e("MainActivity","Command failed",e);runOnUiThread(()->toast("Worker unavailable or command rejected"));}});});}
 private void showSettings(){base();title("Settings");TextInputEditText worker=new TextInputEditText(this);worker.setHint(getString(R.string.worker_url_hint));worker.setText(store.getWorkerUrl());TextInputLayout wbox=new TextInputLayout(this);wbox.addView(worker);root.addView(wbox);TextInputEditText device=new TextInputEditText(this);device.setHint(getString(R.string.device_id_hint));device.setText(store.getDeviceId());TextInputLayout dbox=new TextInputLayout(this);dbox.addView(device);root.addView(dbox);MaterialSwitch audio=new MaterialSwitch(this);audio.setText("Audio");audio.setChecked(store.isAudioEnabled());root.addView(audio);MaterialSwitch hd=new MaterialSwitch(this);hd.setText("HD 1080p when supported");hd.setChecked(store.isHd());root.addView(hd);MaterialSwitch dark=new MaterialSwitch(this);dark.setText("Dark mode");dark.setChecked(store.isDark());root.addView(dark);btn("Save").setOnClickListener(v->{store.setWorkerUrl(String.valueOf(worker.getText()));store.setDeviceId(String.valueOf(device.getText()));store.setAudioEnabled(audio.isChecked());store.setHd(hd.isChecked());store.setDark(dark.isChecked());toast("Settings saved");});btn("Back").setOnClickListener(v->showHome());}
 private boolean hasMediaPermissions(){return ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED&&ContextCompat.checkSelfPermission(this,Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED;} private void requestPermissions(){List<String> p=new ArrayList<>();p.add(Manifest.permission.CAMERA);p.add(Manifest.permission.RECORD_AUDIO);if(Build.VERSION.SDK_INT>=33)p.add(Manifest.permission.POST_NOTIFICATIONS);ActivityCompat.requestPermissions(this,p.toArray(new String[0]),44);} public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==44&&hasMediaPermissions())ContextCompat.startForegroundService(this,new Intent(this,StreamingService.class));else toast("Camera and microphone permissions are required");}
 private void requestBatteryExemption(){if(Build.VERSION.SDK_INT>=23){PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(!pm.isIgnoringBatteryOptimizations(getPackageName()))startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, Uri.parse("package:"+getPackageName())));}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();} protected void onDestroy(){if(renderer!=null)renderer.release();io.shutdownNow();super.onDestroy();}}
