package com.homecam.webrtc;

import android.content.Context;import org.webrtc.*;import java.util.*;

/** Owns the WebRTC PeerConnection, camera capturer, tracks, encoders, and renderer binding. */
public final class HomeCamPeer { public interface Listener{void onLocalDescription(SessionDescription s);void onIceCandidate(IceCandidate c);void onState(PeerConnection.IceConnectionState s);void onRemoteStream(MediaStream s);} private final PeerConnectionFactory factory; private final PeerConnection peer; private VideoCapturer capturer; private VideoTrack videoTrack; private AudioTrack audioTrack; private SurfaceTextureHelper helper; private final EglBase egl=EglBase.create(); private final Context appContext;
 public HomeCamPeer(Context ctx,Listener l){appContext=ctx.getApplicationContext();PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(ctx).createInitializationOptions());factory=PeerConnectionFactory.builder().setVideoEncoderFactory(new DefaultVideoEncoderFactory(egl.getEglBaseContext(),true,true)).setVideoDecoderFactory(new DefaultVideoDecoderFactory(egl.getEglBaseContext())).createPeerConnectionFactory();PeerConnection.RTCConfiguration cfg=new PeerConnection.RTCConfiguration(Collections.singletonList(PeerConnection.IceServer.builder("stun:stun.l.google.com:19302").createIceServer()));peer=factory.createPeerConnection(cfg,new PeerConnection.Observer(){public void onSignalingChange(PeerConnection.SignalingState s){} public void onIceConnectionChange(PeerConnection.IceConnectionState s){l.onState(s);} public void onIceConnectionReceivingChange(boolean b){} public void onIceGatheringChange(PeerConnection.IceGatheringState s){} public void onIceCandidate(IceCandidate c){l.onIceCandidate(c);} public void onIceCandidatesRemoved(IceCandidate[] c){} public void onAddStream(MediaStream s){l.onRemoteStream(s);} public void onRemoveStream(MediaStream s){} public void onDataChannel(DataChannel d){} public void onRenegotiationNeeded(){} public void onAddTrack(RtpReceiver r,MediaStream[] s){} });}
 public EglBase.Context egl(){return egl.getEglBaseContext();} public void startCamera(Context c,boolean front,boolean audio,boolean hd){capturer=createCapturer(front);helper=SurfaceTextureHelper.create("HomeCamCapture",egl.getEglBaseContext());VideoSource vs=factory.createVideoSource(false);capturer.initialize(helper,c,vs.getCapturerObserver());capturer.startCapture(hd?1920:1280,hd?1080:720,30);videoTrack=factory.createVideoTrack("video0",vs);peer.addTrack(videoTrack,Collections.singletonList("homecam")); if(audio){AudioSource as=factory.createAudioSource(new MediaConstraints());audioTrack=factory.createAudioTrack("audio0",as);peer.addTrack(audioTrack,Collections.singletonList("homecam"));}}
 private VideoCapturer createCapturer(boolean front){Camera2Enumerator e=new Camera2Enumerator(appContext);for(String n:e.getDeviceNames())if(front==e.isFrontFacing(n))return e.createCapturer(n,null);throw new IllegalStateException("Requested camera unavailable");}
 public void switchCamera(){ if(capturer instanceof CameraVideoCapturer)((CameraVideoCapturer)capturer).switchCamera(null); } public void setVideo(boolean e){if(videoTrack!=null)videoTrack.setEnabled(e);} public void setAudio(boolean e){if(audioTrack!=null)audioTrack.setEnabled(e);} public void offer(Listener l){peer.createOffer(new Sdp(l),new MediaConstraints());} public void answer(Listener l){peer.createAnswer(new Sdp(l),new MediaConstraints());} public void setRemote(SessionDescription s){peer.setRemoteDescription(new Sdp(null),s);} public void addIce(IceCandidate c){peer.addIceCandidate(c);} public void stop(){try{if(capturer!=null)capturer.stopCapture();}catch(InterruptedException e){Thread.currentThread().interrupt();} if(capturer!=null)capturer.dispose(); if(helper!=null)helper.dispose(); peer.close(); factory.dispose(); egl.release();}
 private final class Sdp implements SdpObserver{private final Listener l;Sdp(Listener l){this.l=l;} public void onCreateSuccess(SessionDescription s){peer.setLocalDescription(this,s); if(l!=null)l.onLocalDescription(s);} public void onSetSuccess(){} public void onCreateFailure(String s){} public void onSetFailure(String s){}}}
