package com.homecam.service;

import android.app.*;import android.content.*;import android.net.*;import android.os.*;import androidx.core.app.NotificationCompat;import com.homecam.R;import com.homecam.database.SettingsStore;import com.homecam.model.Command;import com.homecam.network.WorkerClient;import com.homecam.utils.*;import com.homecam.webrtc.HomeCamPeer;import org.webrtc.*;import java.util.concurrent.*;

/** Foreground service that keeps camera streaming alive while managing WakeLock and reconnect behavior. */
public final class StreamingService extends Service implements HomeCamPeer.Listener { public static final String ACTION_START="com.homecam.START"; public static final String ACTION_STOP="com.homecam.STOP"; public static final String ACTION_SWITCH="com.homecam.SWITCH"; private final ExecutorService io=Executors.newSingleThreadExecutor(); private PowerManager.WakeLock lock; private HomeCamPeer peer; private SettingsStore settings; private String token;
 public void onCreate(){super.onCreate();settings=new SettingsStore(this);createChannel();PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);lock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"HomeCam:stream");}
 public int onStartCommand(Intent i,int flags,int id){String a=i==null?ACTION_START:i.getAction(); if(ACTION_STOP.equals(a)){stopStreaming();stopSelf();return START_NOT_STICKY;} if(ACTION_SWITCH.equals(a)&&peer!=null){peer.switchCamera();return START_STICKY;} startForeground(7,notification()); startStreaming(); return START_STICKY;}
 private void startStreaming(){ if(peer!=null)return; token=Validators.newSessionToken(); if(!lock.isHeld())lock.acquire(6*60*60*1000L); peer=new HomeCamPeer(this,this); try{peer.startCamera(this,true,settings.isAudioEnabled(),settings.isHd()); peer.offer(this);}catch(RuntimeException e){Logger.e("StreamingService","Unable to start camera",e);stopStreaming();}}
 private void stopStreaming(){ if(peer!=null){peer.stop();peer=null;} if(lock!=null&&lock.isHeld())lock.release(); }
 public void onDestroy(){stopStreaming();io.shutdownNow();super.onDestroy();}
 private Notification notification(){PendingIntent stop=PendingIntent.getService(this,1,new Intent(this,StreamingService.class).setAction(ACTION_STOP),PendingIntent.FLAG_IMMUTABLE);PendingIntent sw=PendingIntent.getService(this,2,new Intent(this,StreamingService.class).setAction(ACTION_SWITCH),PendingIntent.FLAG_IMMUTABLE);return new NotificationCompat.Builder(this,"stream").setSmallIcon(R.drawable.ic_notification).setContentTitle(getString(R.string.app_name)).setContentText(getString(R.string.streaming_notification)).setOngoing(true).addAction(R.drawable.ic_notification,getString(R.string.stop),stop).addAction(R.drawable.ic_notification,getString(R.string.switch_camera),sw).build();}
 private void createChannel(){ if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("stream",getString(R.string.channel_streaming),NotificationManager.IMPORTANCE_LOW);c.setDescription(getString(R.string.channel_streaming_desc));getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 public IBinder onBind(Intent intent){return null;} public void onLocalDescription(SessionDescription s){io.execute(()->{try{new WorkerClient(settings.getWorkerUrl()).postOffer(settings.getDeviceId(),token,s);}catch(Exception e){Logger.e("StreamingService","Offer signaling failed",e);}});} public void onIceCandidate(IceCandidate c){io.execute(()->{try{new WorkerClient(settings.getWorkerUrl()).postCandidate(settings.getDeviceId(),token,c);}catch(Exception e){Logger.e("StreamingService","Candidate signaling failed",e);}});} public void onState(PeerConnection.IceConnectionState s){Logger.i("StreamingService","ICE state "+s.name());} public void onRemoteStream(MediaStream s){} }
