const DEVICE = /^HOME[0-9A-Z]{5,24}$/;
const TOKEN = /^[a-fA-F0-9]{64}$/;
const COMMANDS = new Set(['START','STOP','FLASH_ON','FLASH_OFF','FRONT_CAMERA','BACK_CAMERA','ENABLE_AUDIO','DISABLE_AUDIO','HD_ON','HD_OFF','PING']);
const TTL = 120;
export default { async fetch(request, env) { try { const url = new URL(request.url); if (request.method === 'OPTIONS') return cors(new Response(null)); if (url.pathname === '/status' && request.method === 'GET') return status(url, env); if (request.method !== 'POST') return json({error:'method_not_allowed'},405); const body = await request.json(); validateIdentity(body); if (url.pathname === '/offer') return store(env, body, 'offer'); if (url.pathname === '/answer') return store(env, body, 'answer'); if (url.pathname === '/candidate') return candidate(env, body); if (url.pathname === '/command') return command(env, body); return json({error:'not_found'},404); } catch (e) { return json({error:e.message || 'bad_request'},400); } } };
function validateIdentity(b){ if(!b || !DEVICE.test(b.deviceId || '') || !TOKEN.test(b.token || '')) throw new Error('invalid_identity'); }
async function store(env,b,type){ if(typeof b.sdp !== 'string' || b.sdp.length > 200000) throw new Error('invalid_sdp'); await env.SIGNAL_STORE.put(`${b.deviceId}:${type}`, JSON.stringify({type:b.type,sdp:b.sdp,createdAt:Date.now()}), {expirationTtl:TTL}); await touch(env,b.deviceId); return json({ok:true}); }
async function candidate(env,b){ if(typeof b.candidate !== 'string' || b.candidate.length > 4096 || typeof b.sdpMid !== 'string' || !Number.isInteger(b.sdpMLineIndex)) throw new Error('invalid_candidate'); const key = `${b.deviceId}:candidate:${crypto.randomUUID()}`; await env.SIGNAL_STORE.put(key, JSON.stringify({sdpMid:b.sdpMid,sdpMLineIndex:b.sdpMLineIndex,candidate:b.candidate,createdAt:Date.now()}), {expirationTtl:TTL}); await touch(env,b.deviceId); return json({ok:true}); }
async function command(env,b){ if(!COMMANDS.has(b.command)) throw new Error('invalid_command'); const nonce = String(b.nonce || ''); if(nonce.length < 4) throw new Error('invalid_nonce'); const replay = `${b.deviceId}:nonce:${nonce}`; if(await env.SIGNAL_STORE.get(replay)) throw new Error('replay_detected'); await env.SIGNAL_STORE.put(replay,'1',{expirationTtl:TTL}); await env.SIGNAL_STORE.put(`${b.deviceId}:command`, JSON.stringify({command:b.command,createdAt:Date.now()}), {expirationTtl:TTL}); await touch(env,b.deviceId); return json({ok:true}); }
async function status(url,env){ const deviceId=url.searchParams.get('deviceId')||''; const token=url.searchParams.get('token')||''; validateIdentity({deviceId,token}); const [offer,answer,command,lastSeen]=await Promise.all([env.SIGNAL_STORE.get(`${deviceId}:offer`,'json'),env.SIGNAL_STORE.get(`${deviceId}:answer`,'json'),env.SIGNAL_STORE.get(`${deviceId}:command`,'json'),env.SIGNAL_STORE.get(`${deviceId}:lastSeen`)]); return json({deviceId,online:Boolean(lastSeen),offer,answer,command,lastSeen:Number(lastSeen||0)}); }
async function touch(env,deviceId){ await env.SIGNAL_STORE.put(`${deviceId}:lastSeen`, String(Date.now()), {expirationTtl:TTL}); }
function json(v,code=200){ return cors(new Response(JSON.stringify(v),{status:code,headers:{'content-type':'application/json'}})); }
function cors(r){ r.headers.set('access-control-allow-origin','*'); r.headers.set('access-control-allow-methods','GET,POST,OPTIONS'); r.headers.set('access-control-allow-headers','content-type'); return r; }
